### ISSUE TITLE
ControllerDirection type is bool, but DIRECT & REVERSE are ints

### ISSUE THREAD

**Issue by halmos** [Dlloydev/QuickPID#2]
In the constructor, the ControllerDirection type is set to `bool` but the two defs for `DIRECT` and `REVERSE` are integers. 

Note that I'm working with PlatformIO who's compiler might have stricter type matching.

**Comment by Dlloydev** [comment]
This should be a simple fix ... I'll have a chance to look at this tomorrow. Thanks for the feedback!

**Comment by Dlloydev** [comment]
Took a while to get to this ... should be OK now.
