### ISSUE TITLE
Using a digital sensor

### ISSUE THREAD

**Issue by petaflot** [Dlloydev/QuickPID#24]
Using a DS18B20 sensor, which gives me a direct reading of the temperature in Celsius (float)

So "Input" is not an analog pin, but a variable that stores the temperature.

I don't know C++ well enough to understand how the code operates ; looking for clues.

**Comment by Dlloydev** [comment]
Sorry I didn't reply sooner. I don't have an example that gets temperature without using the analog pin, but soon I'll be getting some new hardware and will be able to do testing on a similar setup and update the examples.

**Comment by uzi18** [comment]
Just look on PID_basic example just store/assign your temperatue value in Input variable
