### ISSUE TITLE
Error on relay output example

### ISSUE THREAD

**Issue by MtStable** [Dlloydev/QuickPID#25]
I believe there is an error on the PID_RelayOutput example code line 64. 
Second condition should be Output > (millis() - windowStartTime). Otherwise the on and off periods of the cycle switch places and as the input approaches the output the duty cycle increases.

Original line is as below:
if (((unsigned int)Output > minWindow) && ((unsigned int)Output < (millis() - windowStartTime))) digitalWrite(RELAY_PIN, HIGH);

**Comment by Dlloydev** [comment]
Yes, I agree.
Thanks for pointing this out. On the next update, I'll change line 64 to:
`  if (((unsigned int)Output > minWindow) && ((unsigned int)Output > (millis() - windowStartTime))) digitalWrite(RELAY_PIN, HIGH);`

**Comment by Dlloydev** [comment]
Completed (Version 2.4.7)
