### ISSUE TITLE
Platformio Release

### ISSUE THREAD

**Issue by porkyneal** [Dlloydev/QuickPID#28]
Thanks for updating the original PID library and maintaining it. I came to discuss the output of the PID in relation to #27 and have seen that it has been resolved in a new version, 2.4.7 .

I am not sure that this release has been pushed to Platformio, still showing as 2.4.6.

Again, many thanks.

**Comment by Dlloydev** [comment]
Thanks,
It took a while this time for the update to be picked up by Arduino, but now that it's ready, I've published it to PlatformIO and its ready there immediately.
