### ISSUE TITLE
How to work with input output and setpoint of type float?

### ISSUE THREAD

**Issue by gnalbandian** [Dlloydev/QuickPID#3]
Hi @Dlloydev, 
I'm interested in trying your library with a project of mine which already uses @br3ttb library.

The problem is that my input, output and setpoint are of type float.
I understand the speed gained by using int type, but is there any workaround to make you library backward compatible with @br3ttb's?

Thanks!

**Comment by Dlloydev** [comment]
I've now version 2.2.6 ... changed input, output and setpoint to type float to improve compatibility with no impact on speed.
Also, a recent compile issue due to the previous update for ESP32 has been resolved. 
Thanks for  trying this library!
