### ISSUE TITLE
Negative inputs don't work with QuickPID

### ISSUE THREAD

**Issue by mmcgraw74** [Dlloydev/QuickPID#47]
I'm trying to use QuickPID to control a servo.

The servo signal is a float with a range of +90.0 degrees to -90.0 degrees.

I observe that the QuickPID output doesn't go negative with negative input and negative setpoint.

QuickPID output does go positive with positive input values and positive setpoint, and when the input and setpoint are the same value the output is 0.0 - which is what I expect.

Am I doing something wrong?

**Comment by mmcgraw74** [comment]
An additional observation on QuickPID.

If the positive setpoint is less than the positive input - QuickPID output does not go negative, which would be required to get to the servo position to the lower setpoint.

**Comment by Dlloydev** [comment]
I haven't worked with servo's yet but was wondering if you've set the output limits with something like
` myPID.SetOutputLimits(-255, 255);`

Is there a similar issue when using the Arduino PID library?
 `#include <PID_v1.h>`
