### ISSUE TITLE
Ideal and Series mode of pid + Pb

### ISSUE THREAD

**Issue by Farhankhosravi** [Dlloydev/QuickPID#54]
Hi
i want to know that is there any way to use Ideal / Series mode PID, instead of default parallel mode?
and, is there any way to use Pb (proportional band) instead of Kp?
is there any arduino library with one of these features?...

Thanks

**Comment by Dlloydev** [comment]
Good questions.

For a P or PI controller, the parallel form and the series form are [the same](https://www.20sim.com/webhelp/library_signal_control_pid_control_pidcontrollertypes.php).

I'm not aware of any arduino library that uses proportional band or series form controller mode, however I didn't do an intensive search. Perhaps there's some code examples (non-library) that you could search for.  

I'd like to do some testing with a series form controller myself, but won't get a chance until later this year.

**Comment by Dlloydev** [comment]
Not planned at this time
