### ISSUE TITLE
       Kp gets summed with each compute

### ISSUE THREAD

**Issue by thadwald** [Dlloydev/QuickPID#6]
It appears that your logic sums the proportional contribution with each compute() cycle, which causes windup even with zero Ki..

But maybe I’m missing something.

**Comment by Dlloydev** [comment]
You're right that there's some windup with Kp.  This seems to provide a beneficial effect (better response to step change of setpoint) for PID or PI controllers. Note that the windup reduces to zero as the error approaches zero, so it doesn't directly cause oscillations or overshoot issues. I may need to re-visit the algorithm and do more testing for P or PD controllers.

**Comment by Dlloydev** [comment]
Kp windup issue resolved with new release (QuickPID 2.3.1).
