### ISSUE TITLE
Compiler error on ESP32

### ISSUE THREAD

**Issue by hjd1964** [Dlloydev/QuickPID#68]
I get the following error when compiling on the ESP32 w/ libraries 2.0.7:

c:\Users\hjd19\Documents\Arduino\libraries\QuickPID-master\src\QuickPID.cpp: In constructor 'QuickPID::QuickPID(float*, float*, float*)':
c:\Users\hjd19\Documents\Arduino\libraries\QuickPID-master\src\QuickPID.cpp:62:47: error: '*<unknown>.QuickPID::dispKp' is used uninitialized in this function [-Werror=uninitialized]
                        action = Action::direct) {
                                               ^
...and the same of dispKi, dispKd...

I simply changed the involved default parameters to 0 and all was well, not sure how you want to handle it:

https://github.com/Dlloydev/QuickPID/commit/ad1228b29943dd190a155541474efc4ff1ca995d

**Comment by Dlloydev** [comment]
Thanks for reporting this.
Fixed with new QuickPID release 3.1.6
